kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shamrock2004/argo-demo.git
    targetRevision: main
    path: nginx/
  destination:
    server: https://kubernetes.default.svc  
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
