kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: online_shop_app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shamrock2004/argo-demo.git
    targetRevision: main
    path: .

  destination:
    server: https://172.31.94.48:33893
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
